name: Tests for pull requests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - "**" # matches every branch
      - "!master" # but excludes master

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build for Lighthouse & serve locally
        run: PUBLIC_URL=/ yarn build && (yarn serve&)

      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: "http://127.0.0.1:5000"
          emulatedFormFactor: "all"
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "90"
          minBestPracticesScore: "90"
          minPerformanceScore: "90"
          minSeoScore: "90"

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build the React app
      - name: Build
        run: yarn build
