name: Tests for pull requests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - "**" # matches every branch
      - "!master" # but excludes master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: yarn build

      - name: Run Lighthouse against build dir
        uses: treosh/lighthouse-ci-action@v3
        with:
          # no urls needed - the rc file contains the build dir
          configPath: "./lighthouserc.json"

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build the React app
      - name: Build
        run: yarn build
